#!/usr/bin/python3

# Copyright 2021 SUSE LLC
#
# This file is part of update-server-repo-setup
#
# update-server-repo-setup is free software: you can redistribute it
# and/or modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# update-server-repo-setup is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with update-server-repo-setup.
# If not, see <http://www.gnu.org/licenses/>.
#

import argparse
import json
import os
import sys

# Set up command line argument parsing
argparse = argparse.ArgumentParser(
    description='Script to enable repositorries to mirror'
)
help_msg = 'A designator that will be used to enable repos that have been '
help_msg += 'setup to be enabled on a specific framework. Must match the '
help_msg + 'name used in the configuration exactly'
argparse.add_argument(
    '--cloud',
    dest='framework',
    help=help_msg
)
argparse.add_argument(
    '-d', '--dry-run',
    action='store_true',
    default=False,
    dest='dry_run',
    help='Do not perform any action',
)
argparse.add_argument(
    '-f', '--file',
    default='/etc/rmt-utils/rmt_repository_config.json',
    dest='config_file',
    help='The json configuration file',
    metavar='CONFIGFILE'
)
argparse.add_argument(
    '-l', '--log',
    dest='log_file',
    help='The logfile path, including name, default is stdout',
    metavar='LOGFILE'
)
argparse.add_argument(
    '--verbose',
    action='store_true',
    default=False,
    dest='verbose',
    help='Verbose progress information',
)

args = argparse.parse_args()

if not args.dry_run and os.getuid() != 0:
    print('Script must be run as root', file=sys.stderr)
    sys.exit(1)

# Dry run implies verbose
if args.dry_run:
    args.verbose = True

config = open(args.config_file,'r').read()
mirror_info = json.loads(config)

log = sys.stdout
if args.log_file:
    log = open(args.log_file, 'w')

if not args.dry_run:
    if not os.path.exists('/usr/bin/rmt-cli'):
        print(
            'rmt-cli command not found in /usr/bin cannot enable repositories',
            file=sys.stderr
        )
        sys.exit(1)

# Use markers in our RMT images to figure out the framework
framework_to_use = None
if args.framework:
    framework_to_use = args.framework

all_repo_ids = []
for repository_info in mirror_info:
    repository_id = repository_info.get('id')
    enable_framework = repository_info.get('framework')
    if not enable_framework or enable_framework == framework_to_use:
        if args.verbose:
            log.write('Enable repository with id "%s"\n' % repository_id)
            log.write('\t%s\n' % repository_info.get('description'))
        if not args.dry_run:
            all_repo_ids.append(str(repository_id))

if all_repo_ids:
    chunk_cnt = 0
    status = 0
    last = False
    repo_cnt = 30
    # Chunk the numbers of repos we enable at one time into 30
    # 30 is an arbitrary number
    while 1:
        if len(all_repo_ids) < 30:
            enable_repos = all_repo_ids
            last = True
        else:
            if chunk_cnt*repo_cnt+repo_cnt < len(all_repo_ids):
                enable_repos = all_repo_ids[
                    chunk_cnt*repo_cnt:chunk_cnt*repo_cnt+repo_cnt]
            else:
                enable_repos = all_repo_ids[chunk_cnt*repo_cnt:]
                last = True
        chunk_cnt += 1
        status += os.system('rmt-cli repos enable %s' % ' '.join(enable_repos))
        if last:
            break

    if status:
        print('ERROR: Not all configured repos enabled')

if args.log_file:
    log.close()
